#!/bin/bash

nbs=( $@ )
size=$(( ${#nbs[@]} ** 2))

if [ $size == 1 ]; then
   echo $@
   exit
fi

for i in $(seq 0 $(($size - 1))) 
do
    for j in $(seq 1 ${#nbs[@]})
    do
        ok=$(( ($i & $((2 ** ($j - 1) ))) != 0 ))
        if [ $ok == 1 ]
        then
            echo -n ${nbs[$(($j - 1))]}
        fi
    done
    echo ""
done
