#!/bin/bash

#args=${@:-"l r R a t"}
args="lRt"
dirs="../libft"
options=`./powerset $args`

for option in $options
do
    echo 
    echo `tput setaf 5`avec l\(es\) options $option
    echo -n `tput setaf 2`
	for dir in $dirs
	do
		diff <(ls -lRa $dir) <(./ft_ls $dir)
	done
done
