#!/bin/bash

args=${@:-"l r R a t"}
options=`./powerset $args`
dirs=(".." ".")
#options="lRa"

for option in $options
do
    echo 
    echo `tput setaf 5`avec l\(es\) options $option
    echo -n `tput setaf 2`
	for dir in $dirs
	do
		echo `tput setaf 5`on $dir
		echo -n `tput setaf 2`
		ls -$option $dir > logVrai
		../ft_ls -$option $dir > logMoi
		diff logVrai logMoi
	done
done
